# Generated by Django 5.1.3 on 2024-11-15 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_pet_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pet_profile', to='chat.petsperson')),
            ],
        ),
    ]
