# Generated by Django 5.1.3 on 2024-11-15 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_petprofile'),
        ('chat', '002_create_pets_person'),
    ]

    operations = [
    ]
