# Generated by Django 5.1.3 on 2024-11-15 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_merge_0009_petprofile_002_create_pets_person'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='petsperson',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='petsperson', to=settings.AUTH_USER_MODEL),
        ),
    ]
